sudo: false

language: ruby
rvm:
- 2.2.3

cache:
  directories:
  - vendor

install:
- make depends

script:
- make ci

notifications:
  email:
    on_success: never
    on_failure: change
  slack: votestakes:wlFrOcSeyGrsFf7SvoBftZxE
