sudo: false

language: ruby
rvm:
- 2.2.3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

cache:
  bundler: true
  directories:
  - vendor

install:
- make depends

script:
- make ci

notifications:
  email:
    on_success: never
    on_failure: change
  slack: votestakes:wlFrOcSeyGrsFf7SvoBftZxE
